USE FootballManagementDB;
GO

DROP TABLE IF EXISTS PlayerMatchStatistics;
DROP TABLE IF EXISTS MatchReferee;
DROP TABLE IF EXISTS TournamentTeam;
DROP TABLE IF EXISTS Match;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Coach;
DROP TABLE IF EXISTS Team;
DROP TABLE IF EXISTS Referee;
DROP TABLE IF EXISTS Stadium;
DROP TABLE IF EXISTS Tournament;
DROP TABLE IF EXISTS Country;